### ISSUE TITLE
Source and include files are executable

### ISSUE THREAD

**Issue by wthollingsworth** [The-Fire-Ferrets/Paramourus-Rex#1]
Is there any particular reason this is the case?  It's not a huge deal, I suppose, but I'm not able to open the file in any graphical editor (which I don't often use, but might if I'm browsing the tree in a file explorer).

**Comment by wthollingsworth** [comment]
Nobody really commented here, so I just removed the permissions....

**Comment by africanwarrrior** [comment]
Didn't even realize this was back here, sorry

**Comment by wthollingsworth** [comment]
No worries.
